In [147]:
import pandas as pd
import numpy as np

In [148]:
df = pd.read_csv("../data/raw/listings.csv")

In [149]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 92 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   id                                3818 non-null   int64
 1   listing_url                       3818 non-null   object
 2   scrape_id                         3818 non-null   float64
 3   last_scraped                      3818 non-null   object
 4   name                              3818 non-null   object
 5   summary                           3641 non-null   object
 6   space                             3249 non-null   object
 7   description                       3818 non-null   object
 8   experiences_offered               3818 non-null   object
 9   neighborhood_overview             2786 non-null   object
 10  notes                             2212 non-null   object
 11  transit                           2884 non-null   object
 12  thumbnail_url                     3498 non-null   object
 13  medium_url                        3498 non-null   object
 14  picture_url                       3818 non-null   object
 15  xl_picture_url                    3498 non-null   object
 16  host_id                           3818 non-null   int64
 17  host_url                          3818 non-null   object
 18  host_name                         3816 non-null   object
 19  host_since                        3816 non-null   object
 20  host_location                     3810 non-null   object
 21  host_about                        2959 non-null   object
 22  host_response_time                3295 non-null   object
 23  host_response_rate                3295 non-null   object
 24  host_acceptance_rate              3045 non-null   object
 25  host_is_superhost                 3816 non-null   object
 26  host_thumbnail_url                3816 non-null   object
 27  host_picture_url                  3816 non-null   object
 28  host_neighbourhood                3518 non-null   object
 29  host_listings_count               3816 non-null   float64
 30  host_total_listings_count         3816 non-null   float64
 31  host_verifications                3816 non-null   object
 32  host_has_profile_pic              3816 non-null   object
 33  host_identity_verified            3816 non-null   object
 34  street                            3818 non-null   object
 35  neighbourhood                     3402 non-null   object
 36  neighbourhood_cleansed            3818 non-null   object
 37  neighbourhood_group_cleansed      3818 non-null   object
 38  city                              3818 non-null   object
 39  state                             3818 non-null   object
 40  zipcode                           3811 non-null   object
 41  market                            3818 non-null   object
 42  smart_location                    3818 non-null   object
 43  country_code                      3818 non-null   object
 44  country                           3818 non-null   object
 45  latitude                          3818 non-null   float64
 46  longitude                         3818 non-null   float64
 47  is_location_exact                 3818 non-null   object
 48  property_type                     3817 non-null   object
 49  room_type                         3818 non-null   object
 50  accommodates                      3818 non-null   int64
 51  bathrooms                         3802 non-null   float64
 52  bedrooms                          3812 non-null   float64
 53  beds                              3817 non-null   float64
 54  bed_type                          3818 non-null   object
 55  amenities                         3818 non-null   object
 56  square_feet                       97 non-null     float64
 57  price                             3818 non-null   float64
 58  weekly_price                      2009 non-null   object
 59  monthly_price                     1517 non-null   object
 60  security_deposit                  1866 non-null   object
 61  cleaning_fee                      2788 non-null   object
 62  guests_included                   3818 non-null   int64
 63  extra_people                      3818 non-null   object
 64  minimum_nights                    3818 non-null   int64
 65  maximum_nights                    3818 non-null   int64
 66  calendar_updated                  3818 non-null   object
 67  has_availability                  3818 non-null   object
 68  availability_30                   3818 non-null   int64
 69  availability_60                   3818 non-null   int64
 70  availability_90                   3818 non-null   int64
 71  availability_365                  3818 non-null   int64
 72  calendar_last_scraped             3818 non-null   object
 73  number_of_reviews                 3818 non-null   int64
 74  first_review                      3191 non-null   object
 75  last_review                       3191 non-null   object
 76  review_scores_rating              3171 non-null   float64
 77  review_scores_accuracy            3160 non-null   float64
 78  review_scores_cleanliness         3165 non-null   float64
 79  review_scores_checkin             3160 non-null   float64
 80  review_scores_communication       3167 non-null   float64
 81  review_scores_location            3163 non-null   float64
 82  review_scores_value               3162 non-null   float64
 83  requires_license                  3818 non-null   object
 84  license                           0 non-null      float64
 85  jurisdiction_names                3818 non-null   object
 86  instant_bookable                  3818 non-null   object
 87  cancellation_policy               3818 non-null   object
 88  require_guest_profile_picture     3818 non-null   object
 89  require_guest_phone_verification  3818 non-null   object
 90  calculated_host_listings_count    3818 non-null   int64
 91  reviews_per_month                 3191 non-null   float64
dtypes: float64(19), int64(12), object(61)
memory usage: 2.7+ MB

In [150]:
df.head(10)

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,...,review_scores_value,requires_license,license,jurisdiction_names,instant_bookable,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,reviews_per_month
0,241032,https://www.airbnb.com/rooms/241032,2.016010e+13,1/4/2016,Stylish Queen Anne Apartment,NaN,Make your self at home in this charming one-be...,Make your self at home in this charming one-be...,none,NaN,...,10.0,f,NaN,WASHINGTON,f,moderate,f,f,2,4.07
1,953595,https://www.airbnb.com/rooms/953595,2.016010e+13,1/4/2016,Bright & Airy Queen Anne Apartment,Chemically sensitive? We've removed the irrita...,"Beautiful, hypoallergenic apartment in an extr...",Chemically sensitive? We've removed the irrita...,none,"Queen Anne is a wonderful, truly functional vi...",...,10.0,f,NaN,WASHINGTON,f,strict,t,t,6,1.48
2,3308979,https://www.airbnb.com/rooms/3308979,2.016010e+13,1/4/2016,New Modern House-Amazing water view,New modern house built in 2013. Spectacular s...,"Our house is modern, light and fresh with a wa...",New modern house built in 2013. Spectacular s...,none,Upper Queen Anne is a charming neighborhood fu...,...,10.0,f,NaN,WASHINGTON,f,strict,f,f,2,1.15
3,7421966,https://www.airbnb.com/rooms/7421966,2.016010e+13,1/4/2016,Queen Anne Chateau,A charming apartment that sits atop Queen Anne...,NaN,A charming apartment that sits atop Queen Anne...,none,NaN,...,NaN,f,NaN,WASHINGTON,f,flexible,f,f,1,NaN
4,278830,https://www.airbnb.com/rooms/278830,2.016010e+13,1/4/2016,Charming craftsman 3 bdm house,Cozy family craftman house in beautiful neighb...,Cozy family craftman house in beautiful neighb...,Cozy family craftman house in beautiful neighb...,none,We are in the beautiful neighborhood of Queen ...,...,9.0,f,NaN,WASHINGTON,f,strict,f,f,1,0.89
5,5956968,https://www.airbnb.com/rooms/5956968,2.016010e+13,1/4/2016,Private unit in a 1920s mansion,We're renting out a small private unit of one ...,If you include a bit of your background in you...,We're renting out a small private unit of one ...,none,This part of Queen Anne has wonderful views an...,...,10.0,f,NaN,WASHINGTON,f,strict,f,f,1,2.45
6,1909058,https://www.airbnb.com/rooms/1909058,2.016010e+13,1/4/2016,Queen Anne Private Bed and Bath,Enjoy a quiet stay in our comfortable 1915 Cra...,Enjoy a quiet stay in our comfortable 1915 Cra...,Enjoy a quiet stay in our comfortable 1915 Cra...,none,"Close restaurants, coffee shops and grocery st...",...,10.0,f,NaN,WASHINGTON,f,moderate,f,f,1,2.46
7,856550,https://www.airbnb.com/rooms/856550,2.016010e+13,1/4/2016,Tiny Garden cabin on Queen Anne,"Our tiny cabin is private , very quiet and com...","This cabin was built with Airbnb in mind, Que...","Our tiny cabin is private , very quiet and com...",none,We are centrally located between Downtown and ...,...,10.0,f,NaN,WASHINGTON,f,strict,t,t,5,4.73
8,4948745,https://www.airbnb.com/rooms/4948745,2.016010e+13,1/4/2016,Urban Charm || Downtown || Views,"Nestled in the heart of the city, this space i...","Located in the heart of the city, this space i...","Nestled in the heart of the city, this space i...",none,Walking Score: 92 4 blocks from Kerry Park Fam...,...,10.0,f,NaN,WASHINGTON,f,strict,f,f,1,1.22
9,2493658,https://www.airbnb.com/rooms/2493658,2.016010e+13,1/4/2016,Airy + Bright Queen Anne Apartment,"Beautiful apartment in an extremely safe, quie...",What's special about this place? A beautiful r...,"Beautiful apartment in an extremely safe, quie...",none,"Queen Anne is a wonderful, truly functional vi...",...,9.0,f,NaN,WASHINGTON,f,strict,t,t,6,1.55

In [151]:
df.tail(10)

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,...,review_scores_value,requires_license,license,jurisdiction_names,instant_bookable,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,reviews_per_month
3808,1844791,https://www.airbnb.com/rooms/1844791,2.016010e+13,1/4/2016,Beautiful Craftsman - Fremont 3 Bed,Our charming home in fabulous Upper Fremont is...,This is a classically beautiful Craftsman home...,Our charming home in fabulous Upper Fremont is...,none,Fremont is wonderful; you will love it here. T...,...,9.0,f,NaN,WASHINGTON,f,strict,f,f,2,1.15
3809,6120046,https://www.airbnb.com/rooms/6120046,2.016010e+13,1/4/2016,Lake Veiw Cottage in Fremont,From the deck of this quaint little apartment ...,This one bedroom apartment (Hippy Shack) is de...,From the deck of this quaint little apartment ...,none,This cottage apartment is located just a few b...,...,8.0,f,NaN,WASHINGTON,f,strict,f,f,1,1.18
3810,262764,https://www.airbnb.com/rooms/262764,2.016010e+13,1/4/2016,Fremont Farmhouse,Our 2BR/1 bath home in Fremont's most fun neig...,"1200 ft2 2BR, 1 Bath farmhouse with a large, t...",Our 2BR/1 bath home in Fremont's most fun neig...,none,We love that Fremont is so centrally located t...,...,8.0,f,NaN,WASHINGTON,f,strict,f,f,1,1.56
3811,8578490,https://www.airbnb.com/rooms/8578490,2.016010e+13,1/4/2016,Super Convenient Top Floor Apt,In the true spirit of AirBNB this unit is avai...,The building is older (1970's) so not the mode...,In the true spirit of AirBNB this unit is avai...,none,I am equidistant to Fremont and Wallingford an...,...,10.0,f,NaN,WASHINGTON,f,moderate,f,f,1,0.63
3812,3383329,https://www.airbnb.com/rooms/3383329,2.016010e+13,1/4/2016,OF THE TREE & CLOUDS. KID FRIENDLY!,"Of the Tree & Clouds' ""Roots"" apartment is 8 b...","The 1-bedroom, ground-floor Roots apartment is...","Of the Tree & Clouds' ""Roots"" apartment is 8 b...",none,It's taken me a while to figure out why Fremon...,...,10.0,f,NaN,WASHINGTON,t,moderate,t,t,3,4.01
3813,8101950,https://www.airbnb.com/rooms/8101950,2.016010e+13,1/4/2016,3BR Mountain View House in Seattle,Our 3BR/2BA house boasts incredible views of t...,"Our 3BR/2BA house bright, stylish, and wheelch...",Our 3BR/2BA house boasts incredible views of t...,none,We're located near lots of family fun. Woodlan...,...,8.0,f,NaN,WASHINGTON,f,strict,f,f,8,0.30
3814,8902327,https://www.airbnb.com/rooms/8902327,2.016010e+13,1/4/2016,Portage Bay View!-One Bedroom Apt,800 square foot 1 bedroom basement apartment w...,This space has a great view of Portage Bay wit...,800 square foot 1 bedroom basement apartment w...,none,The neighborhood is a quiet oasis that is clos...,...,10.0,f,NaN,WASHINGTON,f,moderate,f,f,1,2.00
3815,10267360,https://www.airbnb.com/rooms/10267360,2.016010e+13,1/4/2016,Private apartment view of Lake WA,"Very comfortable lower unit. Quiet, charming m...",NaN,"Very comfortable lower unit. Quiet, charming m...",none,NaN,...,NaN,f,NaN,WASHINGTON,f,moderate,f,f,1,NaN
3816,9604740,https://www.airbnb.com/rooms/9604740,2.016010e+13,1/4/2016,Amazing View with Modern Comfort!,Cozy studio condo in the heart on Madison Park...,Fully furnished unit to accommodate most needs...,Cozy studio condo in the heart on Madison Park...,none,Madison Park offers a peaceful slow pace upsca...,...,NaN,f,NaN,WASHINGTON,f,moderate,f,f,1,NaN
3817,10208623,https://www.airbnb.com/rooms/10208623,2.016010e+13,1/4/2016,Large Lakefront Apartment,"All hardwood floors, fireplace, 65"" TV with Xb...",NaN,"All hardwood floors, fireplace, 65"" TV with Xb...",none,NaN,...,NaN,f,NaN,WASHINGTON,f,flexible,f,f,1,NaN

In [152]:
df.isnull()

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,...,review_scores_value,requires_license,license,jurisdiction_names,instant_bookable,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,reviews_per_month
0,False,False,False,False,False,True,False,False,False,True,...,False,False,True,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
3,False,False,False,False,False,False,True,False,False,True,...,True,False,True,False,False,False,False,False,False,True
4,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3813,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
3814,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
3815,False,False,False,False,False,False,True,False,False,True,...,True,False,True,False,False,False,False,False,False,True
3816,False,False,False,False,False,False,False,False,False,False,...,True,False,True,False,False,False,False,False,False,True
3817,False,False,False,False,False,False,True,False,False,True,...,True,False,True,False,False,False,False,False,False,True

In [153]:
df.isnull().sum()

id                                    0
listing_url                           0
scrape_id                             0
last_scraped                          0
name                                  0
                                   ...
cancellation_policy                   0
require_guest_profile_picture         0
require_guest_phone_verification      0
calculated_host_listings_count        0
reviews_per_month                   627
Length: 92, dtype: int64

In [154]:
df["reviews_per_month"].fillna(0, inplace=True)

C:\Users\SUBODH\AppData\Local\Temp\ipykernel_18288\1901275697.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["reviews_per_month"].fillna(0, inplace=True)

In [155]:
df.isnull().sum()

id                                  0
listing_url                         0
scrape_id                           0
last_scraped                        0
name                                0
                                   ..
cancellation_policy                 0
require_guest_profile_picture       0
require_guest_phone_verification    0
calculated_host_listings_count      0
reviews_per_month                   0
Length: 92, dtype: int64

In [156]:
df.drop(['id','host_name'], axis=1, inplace=True)

In [157]:
df.drop_duplicates(inplace=True)

In [158]:
# # Convert 'price' column to numeric (this will force non-numeric values to NaN)
# df['price'] = pd.to_numeric(df['price'], errors='coerce')

# # Handle missing values in 'price' (fill with median or drop rows)
# df['price'].fillna(df['price'].median(), inplace=True)

In [159]:
#Removing Outliers from Price Column
price_threshold = df['price'].quantile(0.99)
df = df[df['price'] < price_threshold]

df.head()

,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,notes,...,review_scores_value,requires_license,license,jurisdiction_names,instant_bookable,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,reviews_per_month
0,https://www.airbnb.com/rooms/241032,2.016010e+13,1/4/2016,Stylish Queen Anne Apartment,NaN,Make your self at home in this charming one-be...,Make your self at home in this charming one-be...,none,NaN,NaN,...,10.0,f,NaN,WASHINGTON,f,moderate,f,f,2,4.07
1,https://www.airbnb.com/rooms/953595,2.016010e+13,1/4/2016,Bright & Airy Queen Anne Apartment,Chemically sensitive? We've removed the irrita...,"Beautiful, hypoallergenic apartment in an extr...",Chemically sensitive? We've removed the irrita...,none,"Queen Anne is a wonderful, truly functional vi...",What's up with the free pillows? Our home was...,...,10.0,f,NaN,WASHINGTON,f,strict,t,t,6,1.48
3,https://www.airbnb.com/rooms/7421966,2.016010e+13,1/4/2016,Queen Anne Chateau,A charming apartment that sits atop Queen Anne...,NaN,A charming apartment that sits atop Queen Anne...,none,NaN,NaN,...,NaN,f,NaN,WASHINGTON,f,flexible,f,f,1,0.00
4,https://www.airbnb.com/rooms/278830,2.016010e+13,1/4/2016,Charming craftsman 3 bdm house,Cozy family craftman house in beautiful neighb...,Cozy family craftman house in beautiful neighb...,Cozy family craftman house in beautiful neighb...,none,We are in the beautiful neighborhood of Queen ...,Belltown,...,9.0,f,NaN,WASHINGTON,f,strict,f,f,1,0.89
5,https://www.airbnb.com/rooms/5956968,2.016010e+13,1/4/2016,Private unit in a 1920s mansion,We're renting out a small private unit of one ...,If you include a bit of your background in you...,We're renting out a small private unit of one ...,none,This part of Queen Anne has wonderful views an...,Let me know if you need anything or have sugge...,...,10.0,f,NaN,WASHINGTON,f,strict,f,f,1,2.45

In [160]:
min_nights_threshold = df['minimum_nights'].quantile(0.99)
df = df[df['minimum_nights'] < min_nights_threshold]

In [161]:
df['last_review'] = pd.to_datetime(df['last_review'])

In [162]:
df.head()

,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,notes,...,review_scores_value,requires_license,license,jurisdiction_names,instant_bookable,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,reviews_per_month
0,https://www.airbnb.com/rooms/241032,2.016010e+13,1/4/2016,Stylish Queen Anne Apartment,NaN,Make your self at home in this charming one-be...,Make your self at home in this charming one-be...,none,NaN,NaN,...,10.0,f,NaN,WASHINGTON,f,moderate,f,f,2,4.07
1,https://www.airbnb.com/rooms/953595,2.016010e+13,1/4/2016,Bright & Airy Queen Anne Apartment,Chemically sensitive? We've removed the irrita...,"Beautiful, hypoallergenic apartment in an extr...",Chemically sensitive? We've removed the irrita...,none,"Queen Anne is a wonderful, truly functional vi...",What's up with the free pillows? Our home was...,...,10.0,f,NaN,WASHINGTON,f,strict,t,t,6,1.48
3,https://www.airbnb.com/rooms/7421966,2.016010e+13,1/4/2016,Queen Anne Chateau,A charming apartment that sits atop Queen Anne...,NaN,A charming apartment that sits atop Queen Anne...,none,NaN,NaN,...,NaN,f,NaN,WASHINGTON,f,flexible,f,f,1,0.00
4,https://www.airbnb.com/rooms/278830,2.016010e+13,1/4/2016,Charming craftsman 3 bdm house,Cozy family craftman house in beautiful neighb...,Cozy family craftman house in beautiful neighb...,Cozy family craftman house in beautiful neighb...,none,We are in the beautiful neighborhood of Queen ...,Belltown,...,9.0,f,NaN,WASHINGTON,f,strict,f,f,1,0.89
5,https://www.airbnb.com/rooms/5956968,2.016010e+13,1/4/2016,Private unit in a 1920s mansion,We're renting out a small private unit of one ...,If you include a bit of your background in you...,We're renting out a small private unit of one ...,none,This part of Queen Anne has wonderful views an...,Let me know if you need anything or have sugge...,...,10.0,f,NaN,WASHINGTON,f,strict,f,f,1,2.45

In [163]:
print("\nData after Cleaning")
df.describe()

Data after Cleaning

,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,beds,...,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,calculated_host_listings_count,reviews_per_month
count,3.738000e+03,3.738000e+03,3736.000000,3736.000000,3738.000000,3738.000000,3738.000000,3722.000000,3732.000000,3737.000000,...,3108.000000,3097.000000,3102.000000,3097.000000,3104.00000,3100.000000,3099.000000,0.0,3738.000000,3738.000000
mean,2.016010e+13,1.580315e+07,7.138919,7.138919,47.628877,-122.332967,3.303638,1.242746,1.282422,1.709125,...,94.505148,9.634162,9.552224,9.783662,9.80799,9.606774,9.452404,NaN,2.966292,1.754419
min,2.016010e+13,4.193000e+03,1.000000,1.000000,47.505088,-122.417219,1.000000,0.000000,0.000000,1.000000,...,20.000000,2.000000,3.000000,2.000000,2.00000,4.000000,2.000000,NaN,1.000000,0.000000
25%,2.016010e+13,3.183090e+06,1.000000,1.000000,47.609075,-122.354293,2.000000,1.000000,1.000000,1.000000,...,93.000000,9.000000,9.000000,10.000000,10.00000,9.000000,9.000000,NaN,1.000000,0.320000
50%,2.016010e+13,1.056468e+07,1.000000,1.000000,47.623546,-122.328740,3.000000,1.000000,1.000000,1.000000,...,96.000000,10.000000,10.000000,10.000000,10.00000,10.000000,10.000000,NaN,1.000000,1.125000
75%,2.016010e+13,2.596572e+07,3.000000,3.000000,47.662921,-122.310499,4.000000,1.000000,2.000000,2.000000,...,99.000000,10.000000,10.000000,10.000000,10.00000,10.000000,10.000000,NaN,2.000000,2.687500
max,2.016010e+13,5.320861e+07,502.000000,502.000000,47.733358,-122.240607,16.000000,8.000000,7.000000,15.000000,...,100.000000,10.000000,10.000000,10.000000,10.00000,10.000000,10.000000,NaN,37.000000,12.150000
std,0.000000e+00,1.462036e+07,28.841964,28.841964,0.043237,0.031803,1.915416,0.565854,0.845048,1.099545,...,6.610135,0.701720,0.801691,0.600133,0.57096,0.630426,0.750238,NaN,5.931771,1.839192

In [164]:
df.to_csv("../data/processed/airbnb_cleaned.csv", index=False)

In [165]:
print("Data Cleaning Completed!")

Data Cleaning Completed!